---
- name: Bootstrap Main Node
  hosts: main
  become: yes
  vars:
    listen_address: 0.0.0.0
    listen_port: 9000
    # lsb_releassse": "{{ ansible_distribution_release }}"


  tasks:
    # - name: install requirements for Grafana
  # - name: Update and upgrade apt packages
  #   apt:
  #   # upgrade: yes
  #     update_cache: yes
  #     cache_valid_time: 3600
  - name: "Ansible | Print 'lsb_release'"
    debug:
      msg: "{{ ansible_distribution_release }}"
  
  - name: Installing apt-transport-https software-properties-common and JDK 11
    ansible.builtin.apt:
      name: 
      - apt-transport-https
      - software-properties-common
      - openjdk-11-jre
      - gnupg
      - gpg
      update_cache: yes

    #TERRAFORM INSTALL
  - name: Download Apt Key - TF
    ansible.builtin.get_url:
      url: "https://apt.releases.hashicorp.com/gpg"
      dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
      # mode: '0644'
      # force: true
  - name: Add TF repo to sources.list
    ansible.builtin.apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
      filename: hashicorp.list
      state: present
  - name: Update apt cache and install Terraform
    ansible.builtin.apt:
      name: terraform
      update_cache: yes

# {{ ansible_distribution_release }}
# deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
      # https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip
    #GRAFANA INSTALL
  - name: Download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: Add Grafna repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: present
  - name: Update apt cache and install Grafana
    ansible.builtin.apt:
      name: grafana
      update_cache: yes
  - name: Ensure Grafana is started and enabled
    ansible.builtin.systemd:
      name: grafana-server
      enabled: true
      state: started
  - name: Download Prometheus
    ansible.builtin.get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu
      # mode: '0440'
  - name: Extra Prom resources
    ansible.builtin.unarchive:
      src: prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu
      remote_src: yes
  - name: create Prom Group
    ansible.builtin.group:
      name: prometheus
      state: present
  - name: Create Prom User
    ansible.builtin.user:
      name: prometheus
      group: prometheus
      shell: /sbin/nologin
  - name: Create Prom Directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: yes
      owner: prometheus
      group: prometheus
      mode: '0755'
    loop:
    - /etc/prometheus
    - /etc/prometheus/rules
    - /etc/prometheus/rules.d
    - /etc/prometheus/files_sd
    - /var/lib/prometheus

  # - name: Setting Permissions
  - name: Copy Files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /usr/local/bin
      remote_src: yes
      owner: prometheus
      group: prometheus
      mode: '0755'
    loop:
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/prometheus
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/promtool
  - name: Copy Files
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /etc/prometheus
      remote_src: yes
    loop:
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/consoles
      - /home/ubuntu/prometheus-2.30.3.linux-amd64/console_libraries

  - name: Create Config File
    ansible.builtin.template:
      src: prometheus.yml.j2
      dest: /etc/prometheus/prometheus.yml
  - name: Create Systemd File
    ansible.builtin.template:
      src: prometheus.service
      dest: /etc/systemd/system/prometheus.service
  # - name: Create Systemd File
  - name: Ensure Prometheus is Started
    ansible.builtin.systemd:
      name: prometheus
      enabled: true
      state: started





